### ISSUE TITLE
Update example documentation in Coalfire-AWS-RAMPpak to use subnets of type(map)

### ISSUE THREAD

**Issue by tkennedy-cf** [Coalfire-CF/Coalfire-AWS-RAMPpak#22]
**Is your feature request related to a problem? Please describe.**
Upon the recent upgrade to the `terraform-aws-vpc-nfw` module we need to update the example documentation to use the new subnets output variable of type(map).

Before: `subnet[0]`
After: `subnet["dmz"]`

**Additional context**

**Comment by kourosh-forti-hands** [comment]
https://github.com/Coalfire-CF/Coalfire-AWS-RAMPpak/pull/23
